// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cursce.Data;

#nullable disable

namespace cursce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212141950_adadada2")]
    partial class adadada2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cursce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLegend")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CauseOfDeath = "Застрелился на смерть ха-ха",
                            IsLegend = true,
                            Name = "Курт",
                            Surname = "Кобейн",
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            CauseOfDeath = "Передозик",
                            IsLegend = true,
                            Name = "Хит",
                            Surname = "Леджер",
                            Year = 2025
                        },
                        new
                        {
                            Id = 3,
                            CauseOfDeath = "Застрелили за то что пиздл много",
                            IsLegend = true,
                            Name = "Джон",
                            Surname = "Кенеди",
                            Year = 2025
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
